# Generated by Django 3.2.3 on 2023-01-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
